<?php

return [
    'items' => [
        [
            'label' => 'Accueil',
            'href' => '/',
            'roles' => [],
        ],
        [
            'label' => 'Authentification et sécurité',
            'href' => '#authentification-securite',
            'roles' => ['Super Administrator', 'Administrator'],
            'children' => [
                ['label' => 'Utilisateurs', 'href' => '#utilisateurs', 'roles' => ['Super Administrator', 'Administrator']],
                ['label' => 'Rôles', 'href' => '#roles', 'roles' => ['Super Administrator', 'Administrator']],
                ['label' => 'Permissions', 'href' => '#permissions', 'roles' => ['Super Administrator', 'Administrator']],
                ['label' => 'Sessions', 'href' => '#sessions', 'roles' => ['Super Administrator', 'Administrator']],
                ['label' => 'Journal d\'audit', 'href' => '#audit-logs', 'roles' => ['Super Administrator', 'Administrator']],
            ],
        ],
        [
            'label' => 'Académique',
            'href' => '#academique',
            'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant'],
            'children' => [
                ['label' => 'Étudiants', 'href' => '#etudiants', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
                ['label' => 'Enseignants', 'href' => '#enseignants', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
                ['label' => 'Filières', 'href' => '#filieres', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                ['label' => 'Niveaux', 'href' => '#niveaux', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                ['label' => 'Semestres', 'href' => '#semestres', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                ['label' => 'UE', 'href' => '#ue', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                ['label' => 'ECUE', 'href' => '#ecue', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                ['label' => 'Emplois du temps', 'href' => '#emplois-du-temps', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                ['label' => 'Notes', 'href' => '#notes', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
                ['label' => 'Absences', 'href' => '#absences', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
                ['label' => 'Soutenances', 'href' => '#soutenances', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
            ],
        ],
        [
            'label' => 'Scolarité',
            'href' => '#scolarite',
            'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité'],
            'children' => [
                ['label' => 'Inscriptions', 'href' => '#inscriptions', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
                ['label' => 'Réinscriptions', 'href' => '#reinscriptions', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
                ['label' => 'Documents académiques', 'href' => '#documents-academiques', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
                ['label' => 'Sanctions', 'href' => '#sanctions', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
                ['label' => 'Reports', 'href' => '#reports', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
                ['label' => 'Abandons', 'href' => '#abandons', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
            ],
        ],
        [
            'label' => 'Finance',
            'href' => '#finance',
            'roles' => ['Super Administrator', 'Administrator', 'Comptable'],
            'children' => [
                ['label' => 'Frais', 'href' => '#frais', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                ['label' => 'Paiements', 'href' => '#paiements', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                ['label' => 'Remises', 'href' => '#remises', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                ['label' => 'Bourses', 'href' => '#bourses', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                ['label' => 'Remboursements', 'href' => '#remboursements', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                ['label' => 'Journaux comptables', 'href' => '#journaux-comptables', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
            ],
        ],
        [
            'label' => 'Communication',
            'href' => '#communication',
            'roles' => ['Super Administrator', 'Administrator', 'Chargé de Communication'],
            'children' => [
                ['label' => 'Messages', 'href' => '#messages', 'roles' => ['Super Administrator', 'Administrator', 'Chargé de Communication']],
                ['label' => 'SMS', 'href' => '#sms', 'roles' => ['Super Administrator', 'Administrator', 'Chargé de Communication']],
                ['label' => 'Emails', 'href' => '#emails', 'roles' => ['Super Administrator', 'Administrator', 'Chargé de Communication']],
                ['label' => 'Notifications', 'href' => '#notifications', 'roles' => ['Super Administrator', 'Administrator', 'Chargé de Communication']],
                ['label' => 'Campagnes', 'href' => '#campagnes-sms', 'roles' => ['Super Administrator', 'Administrator', 'Chargé de Communication']],
            ],
        ],
        [
            'label' => 'Ressources humaines',
            'href' => '#ressources-humaines',
            'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines'],
            'children' => [
                ['label' => 'Personnel', 'href' => '#rh-personnel', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Contrats', 'href' => '#rh-contrats', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Congés', 'href' => '#rh-conges', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Salaires', 'href' => '#rh-salaires', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Vacataires', 'href' => '#rh-vacataires', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Évaluations', 'href' => '#rh-evaluations', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
            ],
        ],
        [
            'label' => 'Infirmerie',
            'href' => '#infirmerie',
            'roles' => ['Super Administrator', 'Administrator', 'Infirmerie'],
            'children' => [
                ['label' => 'Dossiers médicaux', 'href' => '#dossiers-medicaux', 'roles' => ['Super Administrator', 'Administrator', 'Infirmerie']],
                ['label' => 'Consultations', 'href' => '#consultations', 'roles' => ['Super Administrator', 'Administrator', 'Infirmerie']],
                ['label' => 'Vaccinations', 'href' => '#vaccinations', 'roles' => ['Super Administrator', 'Administrator', 'Infirmerie']],
                ['label' => 'Ordonnances', 'href' => '#ordonnances', 'roles' => ['Super Administrator', 'Administrator', 'Infirmerie']],
            ],
        ],
        [
            'label' => 'Administration',
            'href' => '#administration',
            'roles' => ['Super Administrator', 'Administrator'],
            'children' => [
                ['label' => 'Partenaires', 'href' => '#partenaires', 'roles' => ['Super Administrator', 'Administrator']],
                ['label' => 'Salles', 'href' => '#salles', 'roles' => ['Super Administrator', 'Administrator']],
                ['label' => 'Bâtiments', 'href' => '#batiments', 'roles' => ['Super Administrator', 'Administrator']],
                ['label' => 'Équipements', 'href' => '#equipements', 'roles' => ['Super Administrator', 'Administrator']],
            ],
        ],
        [
            'label' => 'Reporting',
            'href' => '#reporting',
            'roles' => ['Super Administrator', 'Administrator'],
            'children' => [
                ['label' => 'Tableaux de bord', 'href' => '#tableaux-de-bord', 'roles' => ['Super Administrator', 'Administrator']],
                ['label' => 'Exports', 'href' => '#exports', 'roles' => ['Super Administrator', 'Administrator']],
                ['label' => 'Indicateurs', 'href' => '#indicateurs', 'roles' => ['Super Administrator', 'Administrator']],
            ],
        ],
        [
            'label' => 'Paramètres',
            'href' => '#parametres',
            'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines'],
            'children' => [
                ['label' => 'Années universitaires', 'href' => '#annees-universitaires', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Paramètres', 'href' => '#parametres-systeme', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Sauvegardes', 'href' => '#sauvegardes', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
            ],
        ],
        [
            'label' => 'Tableau de bord intelligent',
            'href' => '#dashboard-intelligent',
            'roles' => ['Super Administrator', 'Administrator'],
            'children' => [
                [
                    'label' => 'Indicateurs étudiants',
                    'href' => '#indicateurs-etudiants',
                    'roles' => ['Super Administrator', 'Administrator'],
                    'children' => [
                        ['label' => 'Effectif global', 'href' => '#effectif-global', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Nouveaux inscrits', 'href' => '#nouveaux-inscrits', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Diplômés', 'href' => '#diplomes', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Étudiants étrangers', 'href' => '#etudiants-etrangers', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Nationalités', 'href' => '#nationalites', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Répartition Homme/Femme', 'href' => '#repartition-homme-femme', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Boursiers', 'href' => '#boursiers', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Étudiants en difficulté', 'href' => '#etudiants-en-difficulte', 'roles' => ['Super Administrator', 'Administrator']],
                    ],
                ],
                [
                    'label' => 'Indicateurs académiques',
                    'href' => '#indicateurs-academiques',
                    'roles' => ['Super Administrator', 'Administrator'],
                    'children' => [
                        ['label' => 'Avancement des cours', 'href' => '#avancement-cours', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Nombre de cours', 'href' => '#nombre-cours', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'UE validées', 'href' => '#ue-validees', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Moyennes générales', 'href' => '#moyennes-generales', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Soutenances programmées', 'href' => '#soutenances-programmees', 'roles' => ['Super Administrator', 'Administrator']],
                    ],
                ],
                [
                    'label' => 'Indicateurs financiers',
                    'href' => '#indicateurs-financiers',
                    'roles' => ['Super Administrator', 'Administrator'],
                    'children' => [
                        ['label' => 'Chiffre d\'affaires', 'href' => '#chiffre-affaires', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Montants encaissés', 'href' => '#montants-encaisses', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Restes à payer', 'href' => '#restes-a-payer', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Créances', 'href' => '#creances', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Encaissements du jour', 'href' => '#encaissements-du-jour', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Évolution mensuelle', 'href' => '#evolution-mensuelle', 'roles' => ['Super Administrator', 'Administrator']],
                    ],
                ],
                [
                    'label' => 'Ressources humaines',
                    'href' => '#dashboard-rh',
                    'roles' => ['Super Administrator', 'Administrator'],
                    'children' => [
                        ['label' => 'Personnel', 'href' => '#personnel', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Contrats', 'href' => '#contrats', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Congés', 'href' => '#conges', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Salaires', 'href' => '#salaires', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Vacataires', 'href' => '#vacataires', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Évaluations', 'href' => '#evaluations', 'roles' => ['Super Administrator', 'Administrator']],
                    ],
                ],
                [
                    'label' => 'Communication',
                    'href' => '#dashboard-communication',
                    'roles' => ['Super Administrator', 'Administrator'],
                    'children' => [
                        ['label' => 'SMS envoyés', 'href' => '#sms-envoyes', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Emails envoyés', 'href' => '#emails-envoyes', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Notifications', 'href' => '#notifications', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Messages non lus', 'href' => '#messages-non-lus', 'roles' => ['Super Administrator', 'Administrator']],
                    ],
                ],
                [
                    'label' => 'KPI',
                    'href' => '#kpi',
                    'roles' => ['Super Administrator', 'Administrator'],
                    'children' => [
                        ['label' => 'Graphiques', 'href' => '#graphiques', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Histogrammes', 'href' => '#histogrammes', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Courbes', 'href' => '#courbes', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Diagrammes circulaires', 'href' => '#diagrammes-circulaires', 'roles' => ['Super Administrator', 'Administrator']],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Administration',
            'href' => '#admin',
            'roles' => ['Super Administrator', 'Administrator'],
            'children' => [
                ['label' => 'Préinscription en ligne', 'href' => '#preinscription-en-ligne', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
                ['label' => 'Téléversement des pièces', 'href' => '#televersement-pieces', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
                ['label' => 'Paiement des frais', 'href' => '#paiement-des-frais', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
                ['label' => 'Validation', 'href' => '#validation', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
                ['label' => 'Génération automatique du matricule', 'href' => '#generation-matricule', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
                ['label' => 'Impression de la fiche', 'href' => '#impression-fiche', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Responsable de la scolarité']],
            ],
        ],
        [
            'label' => 'Gestion académique',
            'href' => '#gestion-academique',
            'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant'],
            'children' => [
                [
                    'label' => 'Filières',
                    'href' => '#filieres',
                    'roles' => ['Super Administrator', 'Administrator', 'Responsable académique'],
                    'children' => [
                        ['label' => 'Création', 'href' => '#filieres-creation', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                        ['label' => 'Modification', 'href' => '#filieres-modification', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                        ['label' => 'Suppression', 'href' => '#filieres-suppression', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                    ],
                ],
                [
                    'label' => 'Niveaux',
                    'href' => '#niveaux',
                    'roles' => ['Super Administrator', 'Administrator', 'Responsable académique'],
                    'children' => [
                        ['label' => 'Licence', 'href' => '#niveau-licence', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                        ['label' => 'Master', 'href' => '#niveau-master', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                        ['label' => 'Doctorat', 'href' => '#niveau-doctorat', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                    ],
                ],
                [
                    'label' => 'Programmes',
                    'href' => '#programmes',
                    'roles' => ['Super Administrator', 'Administrator', 'Responsable académique'],
                    'children' => [
                        ['label' => 'UE', 'href' => '#programmes-ue', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                        ['label' => 'ECUE', 'href' => '#programmes-ecue', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                        ['label' => 'Crédits', 'href' => '#programmes-credits', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                        ['label' => 'Semestres', 'href' => '#programmes-semestres', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                    ],
                ],
                [
                    'label' => 'Emplois du temps',
                    'href' => '#emplois-du-temps',
                    'roles' => ['Super Administrator', 'Administrator', 'Responsable académique'],
                    'children' => [
                        ['label' => 'Génération automatique', 'href' => '#edt-generation-automatique', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                        ['label' => 'Affectation des salles', 'href' => '#edt-affectation-salles', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                        ['label' => 'Affectation des enseignants', 'href' => '#edt-affectation-enseignants', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique']],
                    ],
                ],
                [
                    'label' => 'Notes',
                    'href' => '#notes',
                    'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant'],
                    'children' => [
                        ['label' => 'Saisie', 'href' => '#notes-saisie', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
                        ['label' => 'Validation', 'href' => '#notes-validation', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
                        ['label' => 'Délibération', 'href' => '#notes-deliberation', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
                        ['label' => 'Classement', 'href' => '#notes-classement', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
                    ],
                ],
                [
                    'label' => 'Soutenances',
                    'href' => '#soutenances',
                    'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant'],
                    'children' => [
                        ['label' => 'Jury', 'href' => '#soutenances-jury', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
                        ['label' => 'Salle', 'href' => '#soutenances-salle', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académique', 'Enseignant']],
                        ['label' => 'Horaire', 'href' => '#soutenances-horaire', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académatique', 'Enseignant']],
                        ['label' => 'Convocation', 'href' => '#soutenances-convocation', 'roles' => ['Super Administrator', 'Administrator', 'Responsable académatique', 'Enseignant']],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Scolarité',
            'href' => '#scolarite',
            'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant'],
            'children' => [
                ['label' => 'Photo', 'href' => '#scolarite-photo', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                ['label' => 'QR Code', 'href' => '#scolarite-qr-code', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                ['label' => 'Carte numérique', 'href' => '#scolarite-carte-numerique', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                ['label' => 'Historique académique', 'href' => '#scolarite-historique-academique', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                ['label' => 'Historique financier', 'href' => '#scolarite-historique-financier', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                ['label' => 'Documents personnels', 'href' => '#scolarite-documents-personnels', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                ['label' => 'Stage', 'href' => '#scolarite-stage', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                ['label' => 'Mémoire', 'href' => '#scolarite-memoire', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                ['label' => 'Diplôme', 'href' => '#scolarite-diplome', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                [
                    'label' => 'Communication',
                    'href' => '#scolarite-communication',
                    'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant'],
                    'children' => [
                        ['label' => 'SMS', 'href' => '#scolarite-communication-sms', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                        ['label' => 'Email', 'href' => '#scolarite-communication-email', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                        ['label' => 'WhatsApp', 'href' => '#scolarite-communication-whatsapp', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                        ['label' => 'Notifications', 'href' => '#scolarite-communication-notifications', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                    ],
                ],
                [
                    'label' => 'Envoi automatique',
                    'href' => '#scolarite-envoi-automatique',
                    'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant'],
                    'children' => [
                        ['label' => 'Paiement des frais', 'href' => '#scolarite-envoi-paiement-frais', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                        ['label' => 'Examens', 'href' => '#scolarite-envoi-examens', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                        ['label' => 'Soutenances', 'href' => '#scolarite-envoi-soutenances', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                        ['label' => 'Absences', 'href' => '#scolarite-envoi-absences', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                        ['label' => 'Résultats', 'href' => '#scolarite-envoi-resultats', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                        ['label' => 'Réinscriptions', 'href' => '#scolarite-envoi-reinscriptions', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Étudiant']],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Finance',
            'href' => '#finance',
            'roles' => ['Super Administrator', 'Administrator', 'Comptable'],
            'children' => [
                [
                    'label' => 'Paiements',
                    'href' => '#paiements',
                    'roles' => ['Super Administrator', 'Administrator', 'Comptable'],
                    'children' => [
                        ['label' => 'Espèces', 'href' => '#paiements-especes', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Mobile Money', 'href' => '#paiements-mobile-money', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Carte bancaire', 'href' => '#paiements-carte-bancaire', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Chèque', 'href' => '#paiements-cheque', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                    ],
                ],
                [
                    'label' => 'Comptabilité',
                    'href' => '#comptabilite',
                    'roles' => ['Super Administrator', 'Administrator', 'Comptable'],
                    'children' => [
                        ['label' => 'Journal', 'href' => '#journal', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Balance', 'href' => '#balance', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Grand Livre', 'href' => '#grand-livre', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                    ],
                ],
                [
                    'label' => 'États financiers',
                    'href' => '#etats-financiers',
                    'roles' => ['Super Administrator', 'Administrator', 'Comptable'],
                    'children' => [
                        ['label' => 'Recettes', 'href' => '#recettes', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Dépenses', 'href' => '#depenses', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Bilan', 'href' => '#bilan', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Trésorerie', 'href' => '#tresorerie', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                    ],
                ],
                [
                    'label' => 'Ressources humaines',
                    'href' => '#finance-rh',
                    'roles' => ['Super Administrator', 'Administrator', 'Comptable'],
                    'children' => [
                        ['label' => 'Personnel', 'href' => '#finance-rh-personnel', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Contrats', 'href' => '#finance-rh-contrats', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Congés', 'href' => '#finance-rh-conges', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Salaires', 'href' => '#finance-rh-salaires', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Vacataires', 'href' => '#finance-rh-vacataires', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                        ['label' => 'Évaluations', 'href' => '#finance-rh-evaluations', 'roles' => ['Super Administrator', 'Administrator', 'Comptable']],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Ressources Humaines',
            'href' => '#rh',
            'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines'],
            'children' => [
                ['label' => 'Personnel', 'href' => '#rh-personnel', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Contrats', 'href' => '#rh-contrats', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Congés', 'href' => '#rh-conges', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Salaires', 'href' => '#rh-salaires', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Vacataires', 'href' => '#rh-vacataires', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
                ['label' => 'Évaluations', 'href' => '#rh-evaluations', 'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines']],
            ],
        ],
        [
            'label' => 'Infirmerie',
            'href' => '#infirmerie',
            'roles' => ['Super Administrator', 'Infirmerie'],
            'children' => [
                ['label' => 'Dossier médical', 'href' => '#dossier-medical', 'roles' => ['Super Administrator', 'Infirmerie']],
                ['label' => 'Consultations', 'href' => '#consultations', 'roles' => ['Super Administrator', 'Infirmerie']],
                ['label' => 'Vaccinations', 'href' => '#vaccinations', 'roles' => ['Super Administrator', 'Infirmerie']],
                ['label' => 'Ordonnances', 'href' => '#ordonnances', 'roles' => ['Super Administrator', 'Infirmerie']],
                ['label' => 'Historique', 'href' => '#historique', 'roles' => ['Super Administrator', 'Infirmerie']],
            ],
        ],
        [
            'label' => 'Recherche scientifique',
            'href' => '#recherche-scientifique',
            'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Chercheur'],
            'children' => [
                ['label' => 'Gestion des mémoires', 'href' => '#gestion-des-memoires', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Chercheur']],
                ['label' => 'Gestion des thèses', 'href' => '#gestion-des-theses', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Chercheur']],
                ['label' => 'Publications', 'href' => '#publications', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Chercheur']],
                ['label' => 'Laboratoires', 'href' => '#laboratoires', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Chercheur']],
                ['label' => 'Encadreurs', 'href' => '#encadreurs', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Chercheur']],
                ['label' => 'Suivi des doctorants', 'href' => '#suivi-des-doctorants', 'roles' => ['Super Administrator', 'Administrator', 'Enseignant', 'Chercheur']],
            ],
        ],
        [
            'label' => 'Assurance qualité',
            'href' => '#assurance-qualite',
            'roles' => ['Super Administrator', 'Administrator', 'Chargé de Qualité'],
            'children' => [
                ['label' => 'Évaluation des enseignants', 'href' => '#evaluation-des-enseignants', 'roles' => ['Super Administrator', 'Administrator', 'Chargé de Qualité']],
                ['label' => 'Évaluation des cours', 'href' => '#evaluation-des-cours', 'roles' => ['Super Administrator', 'Administrator', 'Chargé de Qualité']],
                ['label' => 'Enquêtes de satisfaction', 'href' => '#enquetes-de-satisfaction', 'roles' => ['Super Administrator', 'Administrator', 'Chargé de Qualité']],
                ['label' => 'Tableaux de bord qualité', 'href' => '#tableaux-de-bord-qualite', 'roles' => ['Super Administrator', 'Administrator', 'Chargé de Qualité']],
            ],
        ],
        [
            'label' => 'Rapports',
            'href' => '#rapports',
            'roles' => ['Super Administrator', 'Administrator', 'Comptable', 'Bibliothécaire', 'Chargé de Qualité', 'Chargé de Communication'],
            'children' => [
                ['label' => 'Ministère', 'href' => '#rapports-ministere', 'roles' => ['Super Administrator', 'Administrator', 'Comptable', 'Bibliothécaire', 'Chargé de Qualité', 'Chargé de Communication']],
                ['label' => 'CAMES', 'href' => '#rapports-cames', 'roles' => ['Super Administrator', 'Administrator', 'Comptable', 'Bibliothécaire', 'Chargé de Qualité', 'Chargé de Communication']],
                ['label' => 'Rectorat', 'href' => '#rapports-rectorat', 'roles' => ['Super Administrator', 'Administrator', 'Comptable', 'Bibliothécaire', 'Chargé de Qualité', 'Chargé de Communication']],
                ['label' => 'Conseil scientifique', 'href' => '#rapports-conseil-scientifique', 'roles' => ['Super Administrator', 'Administrator', 'Comptable', 'Bibliothécaire', 'Chargé de Qualité', 'Chargé de Communication']],
                [
                    'label' => 'Export',
                    'href' => '#rapports-export',
                    'roles' => ['Super Administrator', 'Administrator', 'Comptable', 'Bibliothécaire', 'Chargé de Qualité', 'Chargé de Communication'],
                    'children' => [
                        ['label' => 'PDF', 'href' => '#export-pdf', 'roles' => ['Super Administrator', 'Administrator', 'Comptable', 'Bibliothécaire', 'Chargé de Qualité', 'Chargé de Communication']],
                        ['label' => 'Excel', 'href' => '#export-excel', 'roles' => ['Super Administrator', 'Administrator', 'Comptable', 'Bibliothécaire', 'Chargé de Qualité', 'Chargé de Communication']],
                        ['label' => 'Word', 'href' => '#export-word', 'roles' => ['Super Administrator', 'Administrator', 'Comptable', 'Bibliothécaire', 'Chargé de Qualité', 'Chargé de Communication']],
                        ['label' => 'CSV', 'href' => '#export-csv', 'roles' => ['Super Administrator', 'Administrator', 'Comptable', 'Bibliothécaire', 'Chargé de Qualité', 'Chargé de Communication']],
                    ],
                ],
            ],
        ],
        [
            'label' => 'Paramètres',
            'href' => '#parametres',
            'roles' => ['Super Administrator', 'Administrator', 'Ressources Humaines'],
        ],
        [
            'label' => 'Sécurité',
            'href' => '#securite',
            'roles' => ['Super Administrator', 'Administrator'],
            'children' => [
                [
                    'label' => 'Authentification',
                    'href' => '#authentification',
                    'roles' => ['Super Administrator', 'Administrator'],
                    'children' => [
                        ['label' => 'Connexion', 'href' => '#auth-connexion', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Double facteur (2FA)', 'href' => '#auth-2fa', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Réinitialisation du mot de passe', 'href' => '#auth-reset-password', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Gestion des sessions', 'href' => '#auth-sessions', 'roles' => ['Super Administrator', 'Administrator']],
                    ],
                ],
                ['label' => 'Gestion des rôles', 'href' => '#gestion-roles', 'roles' => ['Super Administrator', 'Administrator']],
                [
                    'label' => 'Journalisation',
                    'href' => '#journalisation',
                    'roles' => ['Super Administrator', 'Administrator'],
                    'children' => [
                        ['label' => 'Connexions', 'href' => '#journal-connexions', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Modifications', 'href' => '#journal-modifications', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Suppressions', 'href' => '#journal-suppressions', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Exportations', 'href' => '#journal-exportations', 'roles' => ['Super Administrator', 'Administrator']],
                    ],
                ],
                [
                    'label' => 'Sauvegarde',
                    'href' => '#sauvegarde',
                    'roles' => ['Super Administrator', 'Administrator'],
                    'children' => [
                        ['label' => 'Sauvegarde automatique', 'href' => '#sauvegarde-automatique', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Restauration', 'href' => '#sauvegarde-restauration', 'roles' => ['Super Administrator', 'Administrator']],
                        ['label' => 'Archivage', 'href' => '#sauvegarde-archivage', 'roles' => ['Super Administrator', 'Administrator']],
                    ],
                ],
            ],
        ],
    ],
];
